version: "3.8"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: actix
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    restart: always
    image: "redis:alpine"
    ports:
     - "6379:6379"

  p2p-server:
    image: kulsthl/p2pserver
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on: 
     - postgres
     - redis