version: "3.9"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: actix
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: "redis:alpine"
    ports:
     - "6379:6379"
  p2p-server:
    restart: always
    build: 
     context: .
     dockerfile: "Dockerfile.dev"
    ports:
     - "5000-9999:80"
     - "80:80"
    depends_on: 
     - postgres
     - redis